mongodb:
  image: mongo
  ports: 
    - "3500:27017"
  volumes:
    - /data/db
    
    
connextcms:
  build: .
  dockerfile: Dockerfile
  links:
    - mongodb
  ports:
    - "3000:3000"
  volumes:
    - /home/connextcms/theme