mongodb:
  image: mongo
  ports: 
    - "3500:27017"
  volumes:
    - ./data:/data/db
  command: mongod --smallfiles --logpath=/dev/null # -- quiet
    
connextcms:
  build: .
  dockerfile: Dockerfile
  links:
    - mongodb
  ports:
    - "3000:3000"
  volumes:
    - ./theme:/home/connextcms/theme
    - ./plugins:/home/connextcms/plugins
    - ./public:/home/connextcms/public
    