mongodb-test:
  image: mongo
  ports: 
    - "3500:27017"
  volumes:
    - ./data:/data/db
  command: mongod --smallfiles --logpath=/dev/null # -- quiet
  restart: always
    
connextcms-test:
  build: .
  dockerfile: Dockerfile
  links:
    - mongodb-test
  ports:
    - "3000:3000"
#    - "8080:8080"
  volumes:
    - ./theme:/home/connextcms/theme
    - ./plugins:/home/connextcms/plugins
    - ./public:/home/connextcms/public
  restart: always
    